language: php
php:
  - 5.4
  - 5.5
  - 5.6
install: _ci/install.sh
script: phpunit tests
deploy:
- provider: script
  script: _ci/deploy.sh
  skip_cleanup: true
  on:
    branch: impl-102
- provider: script
  script: _ci/deploy.sh
  skip_cleanup: true
  on:
    tags: true
    branch: master
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a6a547c028c3f4bb44d0
    on_success: always
    on_failure: always
